- added new image - small refactoring, style changes and bug fixes - new output for installation routine - NOTE: features will be implemented in the next minor and major versions. also   big refactoring

diff --git a/chroot-install b/chroot-install
--- a/chroot-install
+++ b/chroot-install
@@ -17,19 +17,24 @@
 #                                                                              #
 # CONTRIBUTORS                                                                 #
 # pierre@pi3rrot.net                                                           #
+# noptrix@nullsecurity.net                                                     #
 #                                                                              #
 ################################################################################
+
 
 # true / false
 FALSE="0"
 TRUE="1"
 
 # return codes
-SUCCESS="1337"
-FAILURE="31337"
+SUCCESS=1337
+FAILURE=31337
 
 # verbose mode - default: quiet
 VERBOSE="/dev/null"
+
+# blackarch-install version
+VERSION="v0.7.5"
 
 # colors
 WHITE="$(tput bold ; tput setaf 7)"
@@ -44,34 +49,42 @@ BLACKARCH_REPO_URL='http://www.blackarch.org/blackarch/$repo/os/$arch'
 # luks global variable
 LUKS="false"
 
+
 # printf white
-wprintf() {
-    fmt=$1
+wprintf()
+{
+    fmt="${1}"
+
     shift
     printf "%s${fmt}%s\n" "${WHITE}" "$@" "${NC}"
 
-    return "${SUCCESS}"
+    return $SUCCESS
 }
+
 
 # print warning
 warn()
 {
-    fmt=${1}
+    fmt="${1}"
+
     shift
     printf "%s[!] WARNING: ${fmt}%s\n" "${RED}" "${@}" "${NC}"
 
-    return "${SUCCESS}"
+    return $SUCCESS
 }
+
 
 # print error and exit
 err()
 {
-    fmt=${1}
+    fmt="${1}"
+
     shift
     printf "%s[-] ERROR: ${fmt}%s\n" "${RED}" "${@}" "${NC}"
 
-    return "${FAILURE}"
+    return $FAILURE
 }
+
 
 # print error and exit
 cri()
@@ -80,180 +93,225 @@ cri()
     shift
     printf "%s[-] CRITICAL: ${fmt}%s\n" "${RED}" "${@}" "${NC}"
 
-    exit "${FAILURE}"
+    exit $FAILURE
+}
+
+
+# leet banner, very important
+banner()
+{
+    printf "%s--==[ blackarch-install %s ]==--%s\n" \
+        "${YELLOW}" "${VERSION}" "${NC}"
+
+    return $SUCCESS
+}
+
+
+# print banner + head
+header()
+{
+    head="${@}"
+
+    clear
+    printf '%*s\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
+    banner
+    printf '%*s\n\n\n' "${COLUMNS:-$(tput cols)}" '' | tr ' ' -
+    wprintf ">> %s\n\n" "${head}"
+
+    return $SUCCESS
 }
 
 
 # usage and help
 usage()
 {
-cat <<EOF
-Usage: $0 <arg> | <misc>
-OPTIONS:
-    -l: Live-ISO install
+    cat << EOF
+usage: $0 <arg> | <misc>
+options:
+    -l: live-iso install
     -r: repository install
     -b: blackman install
     -d: device target [/dev/sda]
-MISC:
+misc:
     -V: print version and exit
     -H: print help and exit
 EOF
-    exit "${SUCCESS}"
+
+    exit $SUCCESS
 }
 
+
+# check environment
 check_env()
 {
-    if [ -f /var/lib/pacman/db.lck ]; then
-        cri "Pacman locked - rm /var/lib/pacman/db.lck"
+    if [ -f /var/lib/pacman/db.lck ]
+    then
+        cri "pacman locked - rm /var/lib/pacman/db.lck"
     fi
 }
 
-# check argument count
-check_argc()
-{
-    return "${SUCCESS}"
-}
 
-# check if required arguments were selected
-check_args()
-{
-    return "${SUCCESS}"
-}
-
-
+# select blackarch repository
 select_ba_repo()
 {
     mirror_file="/tmp/mirror.lst"
     github_url="https://github.com/BlackArch/blackarch/raw/master/mirror/mirror.lst"
 
-    wprintf "[+] Fetching mirror list..."
-    # check wget installed
-    command -v wget >/dev/null 2>&1 ||
-        pacman -S wget --noconfirm
-
+    wprintf "[*] fetching mirror list"
+    # check if wget installed
+    command -v wget >/dev/null 2>&1 || pacman -S wget --noconfirm
     wget -q "${github_url}" -O "${mirror_file}"
-    [ "${?}" != "0" ] && wprintf "[-] wget failed - setting BlackArch repository" &&
-        return "${FAILURE}"
-
-    wprintf "[+] Select BlackArch Repository"
+    if [ "${?}" != "0" ]
+    then
+        err "wget failed - setting BlackArch repository"
+        return $FAILURE
+    fi
 
     count="1"
     local IFS='|'
     ( while read -r country url mirror_name; do
-        wprintf "    [%s] %s - %s" "${count}" "${country}" "${mirror_name}"
-        wprintf "        * %s" "${url}"
+        wprintf "   %s. %s - %s" "${count}" "${country}" "${mirror_name}"
+        wprintf "       * %s" "${url}"
         ((count++))
     done < "${mirror_file}" )
 
-    printf "%sSelect mirror number: " "${WHITE}"; read a
+    printf "%s[?] select mirror number: " "${WHITE}"; read a
 
-    if [ "${a}" -gt "$(wc -l < ${mirror_file})" ]; then
+    if [ "${a}" -gt "$(wc -l < ${mirror_file})" ]
+    then
         # BLACKARCH_REPO_URL gets the default one - choose better next time ;)
-        wprintf "[+] you fucked up man - we select BlackArch for you..."
+        wprintf "[*] you fucked up man - we select BlackArch for you..."
     else
         BLACKARCH_REPO_URL=$(sed -n "${a}p" "${mirror_file}"|cut -d"|" -f2)
-        wprintf "[+] Mirror from '%s' selected" "$(sed -n "${a}p" "${mirror_file}"|cut -d"|" -f3)"
+        wprintf "   -> mirror from '%s' selected" \
+            "$(sed -n "${a}p" "${mirror_file}"|cut -d"|" -f3)"
     fi
 
     # cleaning up
     rm -rf "${mirror_file}"
 
-    return "${SUCCESS}"
+    return $SUCCESS
 }
 
+
+# update the system
 update_system()
 {
-    wprintf "[+] Adding BlackArch Official Repo"
+    wprintf "[*] adding BlackArch repository"
+
     select_ba_repo
-    [ "${?}" == "${FAILURE}" ] &&
-        wprintf "[-] Mirror selection failed - We go with default one..."
+    if [ "${?}" = "$FAILURE" ]
+    then
+        warn "mirror selection failed - we go with default one"
+    fi
 
     curl -s http://blackarch.org/strap.sh | sh
 
-    if ! grep -q "blackarch" /etc/pacman.conf; then
-        printf '[blackarch]\nServer = %s\n' "${BLACKARCH_REPO_URL}" >> /etc/pacman.conf
+    if ! grep -q "blackarch" /etc/pacman.conf
+    then
+        printf '[blackarch]\nServer = %s\n' "${BLACKARCH_REPO_URL}" \
+            >> /etc/pacman.conf
     else
         sed -i "/\[blackarch\]/{ n;s?Server.*?Server = ${BLACKARCH_REPO_URL}?; }" /etc/pacman.conf
     fi
 
     pacman -Syyu --noconfirm
 
-    return "${SUCCESS}"
+    return $SUCCESS
 }
+
 
 # testing
 install_packages_blackman()
 {
     command -v git >/dev/null 2>&1 || pacman -S git --noconfirm
+
     cd /usr/share/
     git clone https://github.com/nrzizrn/blackman
     ln -s /usr/share/blackman/blackman /usr/bin
     blackman -a
 
-    return "${SUCCESS}"
+    return $SUCCESS
 }
 
+
+# install blackarch packages
 install_packages_repo()
 {
     pacman -S blackarch
-    return "${SUCCESS}"
+
+    return $SUCCESS
 }
 
+
+# install grub bootloader
 install_grub()
 {
     pacman -S grub --noconfirm --needed
 
-    # adding blackarch splash
     mv /boot/splash.png /boot/grub/
+
+    sed -i 's/Arch Linux/BlackArch Linux/' /boot/grub/grub.cfg
+
     printf 'GRUB_BACKGROUND="/boot/grub/splash.png"\n' >> /etc/default/grub
 
+    if [ "${LUKS}" == "true" ]
+    then
+        sed -i "s|quiet|cryptdevice=${ROOT_PART}:cryptroot root=/dev/mapper/cryptroot|" /etc/default/grub
+        sed -i 's|"Arch"|"BlackArch"|' /etc/default/grub
+        #sed -i "s|rw  quiet|rw cryptdevice=${ROOT_PART}:cryptroot|" \
+        #  /boot/grub/grub.cfg
+    fi
+
+    grub-install --target=i386-pc "${HD}"
     grub-mkconfig -o /boot/grub/grub.cfg
-    sed -i 's/Arch Linux/BlackArch Linux/' \
-        /boot/grub/grub.cfg
-    "${LUKS}" && sed -i "s?rw  quiet?rw cryptdevice=${ROOT_PART}:cryptboot?" \
-	    /boot/grub/grub.cfg
 
-    grub-install "${HD}"
-
-    return "${SUCCESS}"
+    return $SUCCESS
 }
+
 
 # set passwd check
 set_passwd()
 {
-    user=${1}
+    user="${1}"
 
-    if [ -n "${user}" ]; then
+    if [ -n "${user}" ]
+    then
         passwd "${user}"
     else
         passwd
     fi
 
-    if [ "${?}" != "0" ]; then
-        wprintf "Wrong passwd - try again d00d"
+    if [ "${?}" != "0" ]
+    then
+        wprintf "wrong passwd - please try again"
         set_passwd "${user}"
     else
-        return "${SUCCESS}"
+        return $SUCCESS
     fi
 
-    return "${SUCCESS}"
+    return $SUCCESS
 }
 
+
+# add and configure users
 configure_users()
 {
     printf "%s" "${WHITE}"
-    printf "[+] Setup root password\n"
+
+    printf "[*] setting up root password\n"
     set_passwd
 
     mv /mnt/shell/root/.bashrc /root/
     cp /root/.bashrc /root/.bash_profile
 
-    printf "[+] Do you want to setup a normal user account [y/N]: "; read a
-    if [ "${a}" == "y" ] || [ "${a}" == "Y" ]; then
-        printf "[+] User name: "; read user
+    printf "[?] setup a normal user account [y/N]: "; read a
+    if [ "${a}" == "y" ] || [ "${a}" == "Y" ]
+    then
+        printf "[?] user name: "; read user
         useradd -m -p "" -g users \
             -G "adm,audio,floppy,log,network,rfkill,scanner,storage,optical,power,wheel" \
-            -s /bin/bash "${user}" && printf "[+] User '%s' created\n" "${user}"
+            -s /bin/bash "${user}" && printf "[*] user '%s' created\n" "${user}"
         set_passwd "${user}"
         mv /mnt/shell/user/.bashrc "/home/${user}/"
         cp "/home/${user}/.bashrc" "/home/${user}/.bash_profile"
@@ -265,49 +323,62 @@ configure_users()
 
     printf "%s" "${NC}"
 
-    return "${SUCCESS}"
+    return $SUCCESS
 }
+
 
 # not used atm
-generate_initfs()
+generate_initramfs()
 {
     sed -i 's/block filesystems/block encrypt filesystems/' /etc/mkinitcpio.conf
-    mkinitcpio -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux.img
-    mkinitcpio -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf -g /boot/initramfs-linux-falback.img -S autodetect
+
+    mkinitcpio -p linux
+    #mkinitcpio -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf \
+    #    -g /boot/initramfs-linux.img
+    #mkinitcpio -k /boot/vmlinuz-linux -c /etc/mkinitcpio.conf \
+    #    -g /boot/initramfs-linux-falback.img -S autodetect
     #mkinitcpio -c /etc/mkinitcpio-archiso.conf -g /boot/blackarch-linux.img
 
-    return "${SUCCESS}"
+    return $SUCCESS
 }
 
+
+# set system hostname
 set_hostname()
 {
 
     printf "%s" "${WHITE}"
 
-    printf " -> Set hostname [blackarch]: "
+    printf "[?] set hostname [blackarch]: "
     read hostname
 
-    [ "${hostname}" == "" ] && hostname="blackarch"
+    if [ "${hostname}" == "" ]
+    then
+        hostname="blackarch"
+    fi
 
     printf "%s\n" "${hostname}" > /etc/hostname
 
     printf "%s" "${NC}"
 
-    return "${SUCCESS}"
+    return $SUCCESS
 }
 
+
+# install the system
 install()
 {
     menu_opt=${1}
 
-    wprintf "[+] Installing packages..."
+    header "package installation"
+
     case "${menu_opt}" in
         "live")
-            wprintf "[+] Updating system..."
+            header "system update"
             update_system
             ;;
         "repository")
-            wprintf "[+] Updating system..."
+            header "system update"
             update_system
             install_packages_repo
             ;;
@@ -316,29 +387,29 @@ install()
             ;;
     esac
 
-    wprintf "[+] Configure system users..."
+    header "user configuration"
     configure_users
 
-    "${LUKS}" && wprintf "[+] Re-Generating initfs..."
-    "${LUKS}" && generate_initfs
+    header "initramfs"
+    "${LUKS}" && generate_initramfs
 
-    wprintf "[+] Setting blackarch hostname..."
+    header "hostname setup"
     set_hostname
 
     # set keymaps choosed before silently
     printf "KEYMAP=%s\n" "${KEYMAPS}" > /etc/vconsole.conf
 
-    wprintf "[+] Installing grub..."
+    header "grub installation"
     install_grub
 
     # sync hd
     sync
 
-    printf "%s[+] BlackArch Linux ready! Enjoy!%s\n" "${RED}" "${NC}"
+    printf "%s[*] BlackArch Linux ready! Enjoy!%s\n" "${RED}" "${NC}"
 
-
-    return "${SUCCESS}"
+    return $SUCCESS
 }
+
 
 # parse command line options
 get_opts()
@@ -372,7 +443,7 @@ get_opts()
                 ;;
             V)
                 printf "%s\n" "${VERSION}"
-                exit "${SUCCESS}"
+                exit $SUCCESS
                 ;;
             H)
                 usage
@@ -383,25 +454,22 @@ get_opts()
         esac
     done
 
-    return "${SUCCESS}"
+    return $SUCCESS
 }
 
 
 # controller and program flow
 main()
 {
-    check_argc ${*}
-    get_opts ${*}
-    check_args ${*}
+    get_opts "${@}"
     check_env
-
     install "${opt_arg}"
 
-    return "${SUCCESS}"
+    return $SUCCESS
 }
 
 
 # program start
-main ${*}
+main "${@}"
 
 # EOF
